# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Starling-Tech-Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starling-Tech-Test
    pod 'PromiseKit'
    pod 'Alamofire'

  target 'Starling-Tech-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Starling-Tech-TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
